# Generated by Django 2.2.7 on 2019-11-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default=None, max_length=200, null=True)),
                ('product', models.CharField(default=None, max_length=200, null=True)),
                ('subsector', models.CharField(default=None, max_length=200, null=True)),
                ('price', models.FloatField()),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('user_id', models.CharField(default=None, max_length=200, null=True)),
                ('user_gender', models.CharField(default=None, max_length=200, null=True)),
                ('companion_type', models.CharField(default=None, max_length=200, null=True)),
                ('companion_gender', models.CharField(default=None, max_length=200, null=True)),
                ('sons_age', models.IntegerField(default=0, null=True)),
                ('travel_reason', models.CharField(default=None, max_length=200, null=True)),
                ('type_of_traveler', models.CharField(default=None, max_length=200, null=True)),
                ('origin', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
